const config = require('../../config/config');
const Helpers = require('../utils/helpers');

class EmailService {
  constructor(sheetService) {
    this.sheetService = sheetService;
    this.emailFrom = config.email.from;
    this.emailTo = config.email.to;
  }

  async sendEmailNotification(prompt, answer, customRecipient = null) {
    Helpers.log('Preparing email notification...');
    
    try {
      const recipient = customRecipient || this.emailTo;
      
      if (!recipient) {
        throw new Error('No email recipient specified');
      }

      // Log the email to Google Sheets (since we're using Sheets as our email system)
      const emailLogged = await this.sheetService.logEmailNotification(
        prompt, 
        answer, 
        recipient, 
        this.emailFrom
      );

      if (emailLogged) {
        Helpers.log(`Email notification prepared for: ${recipient}`);
        
        // In a real implementation, you would integrate with an email service here
        // For now, we're using Google Sheets as our notification system
        return this.simulateEmailSend(prompt, answer, recipient);
      } else {
        throw new Error('Failed to log email notification');
      }
    } catch (error) {
      Helpers.log(`Email service error: ${error.message}`, 'error');
      return {
        success: false,
        error: error.message
      };
    }
  }

  async simulateEmailSend(prompt, answer, recipient) {
    // Simulate email sending process
    Helpers.log(`Simulating email send to: ${recipient}`);
    
    // In a real implementation, you would use:
    // - Nodemailer for SMTP
    // - SendGrid API
    // - AWS SES
    // - Or any other email service
    
    const emailSummary = {
      to: recipient,
      from: this.emailFrom,
      subject: `AI Search Result: ${Helpers.truncateText(prompt, 50)}`,
      body: this.formatEmailBody(prompt, answer),
      timestamp: new Date().toISOString(),
      status: 'simulated_sent'
    };

    Helpers.log(`Email simulation complete for: ${recipient}`);
    
    return {
      success: true,
      emailId: `simulated_${Date.now()}`,
      summary: emailSummary,
      message: 'Email notification logged to Google Sheets and ready for sending'
    };
  }

  formatEmailBody(prompt, answer) {
    return `
AI SEARCH RESULT NOTIFICATION

Query: ${prompt}

AI Analysis:
${answer}

---
Generated by Web Search AI Assistant
Timestamp: ${new Date().toISOString()}
    `.trim();
  }

  async batchSendNotifications(results) {
    Helpers.log(`Preparing batch email notifications for ${results.length} results`);
    
    const emailPromises = results.map(result => 
      this.sendEmailNotification(result.prompt, result.answer)
    );

    const results = await Promise.allSettled(emailPromises);
    
    const summary = {
      total: results.length,
      successful: results.filter(r => r.status === 'fulfilled' && r.value.success).length,
      failed: results.filter(r => r.status === 'rejected' || !r.value.success).length
    };

    Helpers.log(`Batch email notification complete: ${summary.successful}/${summary.total} successful`);
    return summary;
  }
}

module.exports = EmailService;